export const suggestionsData: Record<string, Array<string>> = {
  "How to...": [
    "How to build a cozy gaming setup?",
    "How to create viral TikTok content?",
    "How to start a podcast on a budget?",
    "How to curate a sustainable capsule wardrobe?",
    "How to become a competitive Pokemon trainer?",
    "How to design your own video game level?",
    "How to host a successful board game night?",
    "How to create pixel art for beginners?",
  ],
  "Why...": [
    "Why is Baldur's Gate 3 so popular?",
    "Why are Y2K fashion trends coming back?",
    "Why do certain songs go viral on TikTok?",
    "Why are houseplants the new pets?",
    "Why is Pokemon still relevant after 25+ years?",
    "Why do retro games maintain their appeal?",
    "Why do some games become esports while others don't?",
    "Why do we feel nostalgic about certain music?",
  ],
  "Research...": [
    "Research on K-pop's global influence",
    "Research on open-world game design",
    "Research on sustainable streetwear brands",
    "Research on the psychology of binge-watching",
    "Research on Pokemon's impact on pop culture",
    "Research on the evolution of video game graphics",
    "Research on how music affects gaming performance",
    "Research on the rise of VTubers and digital influencers",
  ],
  "What are...": [
    "What are the best indie games of 2023?",
    "What are Taylor Swift's most iconic lyrics?",
    "What are must-watch shows on streaming platforms?",
    "What are the best anime series of all time?",
    "What are the most powerful Pokemon teams for competitive play?",
    "What are the best mechanical keyboards for gamers?",
    "What are the most influential album releases this year?",
    "What are the upcoming manga adaptations to watch?",
  ],
  "Create...": [
    "Create a perfectly curated Spotify playlist",
    "Create an aesthetic room makeover",
    "Create content for your favorite fandom",
    "Create a modern self-care routine",
    "Create the ultimate Pokemon team guide",
    "Create a personalized gaming achievement system",
    "Create a digital art portfolio website",
    "Create a miniature model of your favorite game level",
  ],
  "Explain...": [
    "Explain the Marvel Cinematic Universe timeline",
    "Explain why indie games are thriving",
    "Explain the appeal of BookTok",
    "Explain how streaming is changing entertainment",
    "Explain Pokemon type advantages and team building",
    "Explain the history of rhythm games",
    "Explain how light novels influence anime production",
    "Explain the evolution of storytelling in video games",
  ],
  "Compare...": [
    "Compare PlayStation 5 vs Xbox Series X",
    "Compare different anime streaming services",
    "Compare fast fashion vs thrifting",
    "Compare coffee brewing methods",
    "Compare different Pokemon generations and their design philosophies",
    "Compare various digital art software for beginners",
    "Compare gaming subscriptions and their value",
    "Compare storytelling in Western RPGs vs JRPGs",
  ],
  "Recommend...": [
    "Recommend underrated Netflix shows",
    "Recommend games like Elden Ring",
    "Recommend affordable tech gadgets",
    "Recommend comfort food recipes with a twist",
    "Recommend Pokemon games for different types of players",
    "Recommend cozy indie games for relaxation",
    "Recommend music for different gaming genres",
    "Recommend anime for people who don't usually watch anime",
  ],
  "Pokemon...": [
    "Pokemon team building strategies for beginners",
    "Pokemon cards that are worth investing in",
    "Pokemon regions ranked from best to worst",
    "Pokemon designs that were inspired by real animals",
    "Pokemon that have changed the competitive meta",
    "Pokemon fan theories that make too much sense",
    "Pokemon evolution lines that should have been different",
    "Pokemon spin-off games worth revisiting",
  ],
  "Analyze...": [
    "Analyze the storytelling in The Last of Us",
    "Analyze character development in Studio Ghibli films",
    "Analyze the influence of Pokemon on monster-collecting games",
    "Analyze the evolution of battle royale games",
    "Analyze music trends in the streaming era",
    "Analyze the rise of VR gaming and its future",
    "Analyze fan culture and community building online",
    "Analyze the psychology behind collection mechanics in games",
  ],
  "Discover...": [
    "Discover hidden Easter eggs in Nintendo games",
    "Discover underrated Pokemon abilities and strategies",
    "Discover indie musicians similar to your favorite artists",
    "Discover Japanese street fashion subcultures",
    "Discover the history of your favorite gaming company",
    "Discover DIY mechanical keyboard customization",
    "Discover techniques used by speed runners",
    "Discover upcoming indie games with promising concepts",
  ],
  "Review...": [
    "Review the most surprising movie adaptations of 2023",
    "Review different Pokemon play styles (casual, competitive, collecting)",
    "Review audiophile headphones for gaming and music",
    "Review bookshelf organization systems",
    "Review color theory basics for digital artists",
    "Review storytelling techniques in recent games",
    "Review ergonomic setups for gamers and streamers",
    "Review plant care tips for busy people",
  ],
  "Explore...": [
    "Explore the evolution of Pokemon designs across generations",
    "Explore how video game music has influenced modern composers",
    "Explore worldbuilding techniques in fantasy series",
    "Explore the most innovative indie game mechanics",
    "Explore the history of animation techniques",
    "Explore minimalist approaches to technology use",
    "Explore the connection between fashion and gaming culture",
    "Explore the psychology of collecting in games and real life",
  ],
  "Debate...": [
    "Debate whether legendary Pokemon should be allowed in competitive play",
    "Debate physical vs digital game collections",
    "Debate the impact of remakes vs original content",
    "Debate the value of gaming subscriptions vs buying games",
    "Debate subtitles vs dubbing in anime",
    "Debate the ideal length for story-driven games",
    "Debate artistic vs commercial success in music",
    "Debate the role of difficulty settings in games",
  ],
  "Rank...": [
    "Rank all Pokemon starters from worst to best",
    "Rank Studio Ghibli films by emotional impact",
    "Rank FromSoftware bosses by difficulty",
    "Rank the best character arcs in TV shows",
    "Rank cozy games by their relaxation factor",
    "Rank gaming peripherals by value for money",
    "Rank Marvel Cinematic Universe phases",
    "Rank music genres by gaming compatibility",
  ],
  "List...": [
    "List essential items for a Pokemon card collector",
    "List underappreciated game soundtracks",
    "List best beginner-friendly musical instruments",
    "List upcoming anime releases to watch",
    "List productivity tools for creative people",
    "List DIY projects for gaming room decoration",
    "List books that should be adapted into games",
    "List surprising facts about your favorite game franchise",
  ],
  "Guide to...": [
    "Guide to building your first gaming PC",
    "Guide to understanding Pokemon competitive tiers",
    "Guide to starting a vinyl record collection",
    "Guide to recognizing art styles in animation",
    "Guide to thrifting for vintage fashion",
    "Guide to digital art fundamentals",
    "Guide to creating a smart home entertainment setup",
    "Guide to plant parenthood for beginners",
  ],
  "Critique...": [
    "Critique recent trends in Pokemon game difficulty",
    "Critique the portrayal of mental health in media",
    "Critique open world vs linear game design",
    "Critique fast fashion's influence on style",
    "Critique accessibility in gaming",
    "Critique modern music production techniques",
    "Critique minimalism as a lifestyle philosophy",
    "Critique sequel approaches in different franchises",
  ],
  "History of...": [
    "History of Pokemon competitive metagame shifts",
    "History of animation techniques that changed the industry",
    "History of iconic video game controllers",
    "History of internet meme evolution",
    "History of streetwear fashion movements",
    "History of home console wars",
    "History of influential indie game developers",
    "History of music streaming platforms",
  ],
  "Design...": [
    "Design your perfect Pokemon team with explanations",
    "Design a cozy gaming room on a budget",
    "Design principles for effective Twitch overlays",
    "Design a custom controller concept",
    "Design a merchandise line for your favorite game",
    "Design a perfect daily routine for productivity and hobbies",
    "Design a fantasy game world with unique ecosystems",
    "Design organization systems for collectors",
  ],
  "Theory...": [
    "Theory about Pokemon world economics and ecology",
    "Theory on why certain games age better than others",
    "Theory about the future of cloud gaming",
    "Theory on what makes certain songs go viral",
    "Theory about the psychological appeal of gacha games",
    "Theory on how art direction affects gameplay experience",
    "Theory about the evolution of internet humor",
    "Theory on parasocial relationships with content creators",
  ],
  "Profile of...": [
    "Profile of competitive Pokemon champions and their strategies",
    "Profile of indie developers who changed the industry",
    "Profile of influential anime directors",
    "Profile of musicians who compose for games",
    "Profile of content creators revolutionizing their niche",
    "Profile of artists pushing digital art boundaries",
    "Profile of fashion designers inspired by gaming",
    "Profile of voice actors behind iconic characters",
  ],
};
